### ISSUE TITLE
Log spamming with (RO)Kerbalism and RealAntennas in flight mode

### ISSUE THREAD

**Issue by Gordon-Dry** [DRVeyl/RealAntennas#5] opened 2019-08-08 20:38 UTC
As I don't know if you're already aware of it, I mention it here.

In flight mode this is spammed to the log:

Alternately
```
[Kerbalism]  -> verbose: CommInfo.Init - Kerbalism: CommInfo handler threw exception Exception has been thrown by the target of an invocation.
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IndexOutOfRangeException: Array index is out of range.
  at RealismOverhaul.Utils.Extensions.Format (Single value, System.String unit, Int32 logBase) [0x00000] in <filename unknown>:0 
  at RealismOverhaul.Utils.Extensions.Format (Double value, System.String unit, Int32 logBase) [0x00000] in <filename unknown>:0 
  at RealismOverhaul.Communications.KerbalismIntegration.GetControlPathItem (CommNet.CommLink link) [0x00000] in <filename unknown>:0 
  at RealismOverhaul.Communications.KerbalismIntegration.GetControlPath (.Vessel v, RealismOverhaul.Communications.AntennaInfo antennaInfo) [0x00000] in <filename unknown>:0 
  at RealismOverhaul.Communications.KerbalismIntegration.GetConnectedAntennaInfo (.Vessel v, RealismOverhaul.Communications.AntennaSpecs vesselSpecs, Boolean transmitting) [0x00000] in <filename unknown>:0 
  at RealismOverhaul.Communications.KerbalismIntegration.GetAntennaInfo (.Vessel v, RealismOverhaul.Communications.AntennaSpecs vesselSpecs, Boolean powered, Boolean transmitting) [0x00000] in <filename unknown>:0 
  at RealismOverhaul.Communications.KerbalismIntegration.HandleCommQuery (System.Object kerbalismAntennaInfo, .Vessel vessel) [0x00000] in <filename unknown>:0 
  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:0 
  --- End of inner exception stack trace ---
  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:0 
  at System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) [0x00000] in <filename unknown>:0 
  at KERBALISM.API+CommInfo.Init (KERBALISM.AntennaInfo antennaInfo, .Vessel pv) [0x00000] in <filename unknown>:0 
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

```
followed by the RAKerbalismLink (ofc with situation relevant values)
```
[RAKerbalismLink] Rate: 44.4 Kbps EC: 0.0274  Linked:True  Strength: 1.00  Target: Node: US - Wallops Links=2 : Home  Control  MultiHop  : [+RA] LaunchSiteTrackingStation [1.0 dBi [VHF-Band 150 MHz] [TL:3] BPSK 50.0 Kbps]   [+RA] LaunchSiteTrackingStation [3.0 dBi [UHF-Band 430 MHz] [TL:3] BPSK 50.0 Kbps]   
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
```

As in many cases the same entries of RAKerbalismLink are following each other it does not seem to occur because of a change of that RAKerbalismLink state.
It likely occurs after a given amount of ticks or frames ...

Full log (still in game):
https://www.dropbox.com/s/cfa2va3v72pouqi/output_log.txt%20and%20stuff%202019-08-08-01.zip?dl=1

**Comment by DRVeyl** [comment] 2019-08-08 20:52
The log spam of the link state is intended at this time, as this is still in a debugging period.  There isn't currently a cleaner way to give the user sufficient debug info to assess if the issue is with Kerbalism, RealAntennas, or the combination of the two.

The exception at the top of the issue -- and in general both RealAntennas and RO-NewComms registering with Kerbalism, is something we will fix.

**Comment by DRVeyl** [comment] 2019-08-31 17:18
I think the exception was fixed with a patch in RO's NewComms branch on Aug 19: https://github.com/MikeOnTea/RealismOverhaul/commit/7b2c475ac460e5310e4f55a86cb7c0abcc5edea9

Someone working with the combination of RO's NewComms, Kerbalism, and RealAntennas please confirm.

**Comment by DRVeyl** [comment] 2019-10-27 02:08
Fixed

**Closed by DRVeyl** 2019-10-27 02:08 UTC
