### ISSUE TITLE
Crash when stage separation

### ISSUE THREAD

**Issue by aihaw** [DRVeyl/RealAntennas#27] opened 2020-05-09 19:42 UTC
Hi! Playing under RSS RO RP-1 (CKAN tutorial installation) I have an issue with the early controllable core (the Squad part but modified by RO).
I made my first lunar probe a .4t orbiter/impactor.
Avionics needs 2 of the early cores but for the comms I depend on a single comm16 put at 39 dbi on tech lvl 1, and I deactivated the comms on the two probe cores.

I do my injection burn and when separating from my TLI stage the game crashes with the Unity crash window opening. I'm not really into coding but when scouring the logs I think I found that the crash is related to real antennas.

I made a series of tests, and having the TLI stage underneath doesn't seem to change the issue, so I mainly did them only with a decoupler:
-So, it works with one core, but with two of them it crashes;
-Doesn't matter if I install the comm 16 or not;
-No matter if I enable the comms on any core (in the editor of course) it still crashes when staging;
-changing the cores in the editor and replacing them with new ones does not do the trick...

Here's the paragraph I read in the player.log:

_

> Uploading Crash Report
> OverflowException: Value was either too large or too small for an Int32.
>   at System.Convert.ToInt32 (System.Double value) [0x00084] in <ad04dee02e7e4a85a1299c7ee81c79f6>:0 
>   at RealAntennas.RealAntennaDigital.BestPeerModulator (RealAntennas.RealAntenna rx, System.Double& modRate, System.Double& codeRate) [0x00382] in <740c8bcb1fb74eb3bfd9ab34d53d9182>:0 
>   at RealAntennas.RealAntennaDigital.BestDataRateToPeer (RealAntennas.RealAntenna rx) [0x00001] in <740c8bcb1fb74eb3bfd9ab34d53d9182>:0 
>   at RealAntennas.RACommNetwork.SelectBestAntennaPairs (System.Collections.Generic.List`1[T] fwdList, System.Collections.Generic.List`1[T] revList, RealAntennas.RealAntenna[] bestFwdAntPair, RealAntennas.RealAntenna[] bestRevAntPair, System.Double& FwdDataRate, System.Double& RevDataRate) [0x0003d] in <740c8bcb1fb74eb3bfd9ab34d53d9182>:0 
>   at RealAntennas.RACommNetwork.TryConnect (CommNet.CommNode a, CommNet.CommNode b, System.Double distance, System.Boolean aCanRelay, System.Boolean bCanRelay, System.Boolean bothRelay) [0x000b9] in <740c8bcb1fb74eb3bfd9ab34d53d9182>:0 
>   at RealAntennas.RACommNetwork.SetNodeConnection (CommNet.CommNode a, CommNet.CommNode b) [0x00064] in <740c8bcb1fb74eb3bfd9ab34d53d9182>:0 
>   at CommNet.Network.Net`4[_Net,_Data,_Link,_Path].UpdateNetwork () [0x00038] in <9d71e4043e394d78a6cf9193ad011698>:0 
>   at CommNet.Network.Net`4[_Net,_Data,_Link,_Path].Rebuild () [0x00032] in <9d71e4043e394d78a6cf9193ad011698>:0 
>   at CommNet.CommNetwork.Rebuild () [0x00007] in <9d71e4043e394d78a6cf9193ad011698>:0 
>   at RealAntennas.RACommNetwork.Rebuild () [0x00032] in <740c8bcb1fb74eb3bfd9ab34d53d9182>:0 
>   at CommNet.CommNetNetwork.Update () [0x000d7] in <9d71e4043e394d78a6cf9193ad011698>:0 
> UnityEngine.DebugLogHandler:Internal_LogException(Exception, Object)
> UnityEngine.DebugLogHandler:LogException(Exception, Object)
> ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
> UnityEngine.Logger:LogException(Exception, Object)
> UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)

_

If you need anything else I can provide you with more logs if needed.

Besides that, I'd like to thank you for your contribution to this incredible masterpiece we call realism overhaul :)

**Comment by aihaw** [comment] 2020-05-09 19:59
[Player.log](https://github.com/DRVeyl/RealAntennas/files/4604395/Player.log)

**Comment by aihaw** [comment] 2020-05-09 23:12
Sorry nevermind I finally think it is more related to procedural parts having a decoupler bug...

**Comment by DRVeyl** [comment] 2020-05-10 01:14
That seems likely -- make sure you have the latest ProcParts release.  RA doesn't move craft, and errors like what you posted are interesting but they're usually symptomatic of something else having gone wrong.  I will see about wrapping that with some safer handling.  If you cannot reproduce after updating ProcParts, please close this issue. :)

**Closed** 2020-05-11 12:38 UTC
